apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  containers:
    - name: container-2
      image: nginx:latest
      volumeMounts:
        - name: shared-storage
          mountPath: /data/shared
  volumes:
    - name: shared-storage
      persistentVolumeClaim:
        claimName: shared-pvc
